### ISSUE TITLE
WP: Users 2

### ISSUE THREAD

**Issue by robert-weissgraeber** [letsmeet-click/letsmeet.click#21]
- profile page
  - [x] my profile
  - [ ] /u/`username`
  - [ ] option to add bio
  - [x] option to add profile picture
  - [x] show list of communities the user is member
  - [x] show list of events the user is going / was going
  - [ ] option to optout of being listed for events/communities (later by community/event ?)
