### ISSUE TITLE
WP - notifications

### ISSUE THREAD

**Issue by robert-weissgraeber** [letsmeet-click/letsmeet.click#26]
- [x] notification mail to organizer on new community subscription
- [x] notification mail to organizer on new event yes/no
- [ ] mail to every attendee one day before event
- [ ] mail to every local_organizer two days before event
- [x] mail to every subscriber on event creation
- [x] mail using i.e. https://www.mailgun.com/
